### ISSUE TITLE
Litecoin support

### ISSUE THREAD

**Issue by kaykurokawa** [rnicoll/cate#4]
I'd like to have litecoin support for this, anyone working on it? 
If not , I can put something together. Just didn't want to duplicate any work.

**Comment by rnicoll** [comment]
It's been kept in mind during development, but not actively worked on. You should be able to add support to python-altcoinlib trivially, and then the only issue for Cate should be that it uses Bitcoin Core 0.9 RPC calls to get change addresses. You'll likely have to replace https://github.com/rnicoll/cate/blob/master/cate/tx.py#L118 with a version that understands the client version and uses a standard address for older clients.

Apart from that, should just be a matter of testing.

**Comment by kaykurokawa** [comment]
See pull requests.   

https://github.com/rnicoll/python-altcoinlib/pull/2
https://github.com/rnicoll/cate/pull/5

I was able to succesfully exchange BTC/LTC with it.
